#!/bin/bash
function myfunc { while getopts "a:b:" opt; do case $opt in a) 
                arg1="$OPTARG"
                ;;
            b) arg2="$OPTARG"
                ;;
            \?) echo "Invalid option: -$OPTARG" >&2 exit 1
                ;;
        esac done echo "Argument 1: $arg1" echo "Argument 2: 
    $arg2"
}
myfunc -a argument1 -b argument2
