#!/bin/bash

LOGDIR="/var/log"

echo
echo "=========================================="
echo "          LOG CREATION TOOL               "
echo "=========================================="
echo
echo " CREATE A NEW LOG AND SET PERMISSIONS? "
echo

read -p "mklog:> " mklog

# Log the new log file path
echo "$LOGDIR/$mklog.log" | tee -a /var/log/newlogpaths.log

# Create the new log file
sudo touch "$LOGDIR/$mklog.log" && echo "CREATED $mklog.log in $LOGDIR!" 

echo
echo "  ######  SETTING $LOGDIR/$mklog PERMISSIONS  ######  " 
echo

# Set the file owner and permissions
sudo chown root:adm "$LOGDIR/$mklog.log" && sudo chmod 775 "$LOGDIR/$mklog.log"

echo
echo "sudo chown root:adm '$LOGDIR/$mklog.log'; sudo chmod 775 '$LOGDIR/$mklog.log'"
echo "'$LOGDIR/$mklog.log' PERMISSIONS SET AND IS NOW WRITEABLE FOR SHELL OUTPUT!"
