#!/bin/bash

echo "Lookup New UUID"
sudo blkid

echo '/dev/sda2: UUID="553de830-6b4f-4cfa-a8e0-74beba43ba5f" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="3f4e38bb-6ec8-4dd9-8188-b6aab39b8a67"'
echo '/dev/sda3: UUID="2068e222-9fae-4613-8d6d-79a030e212e8" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="53677faa-a642-468d-86e8-4340d6e9b37f"'

echo 'Edit: /etc/fstab with NEW UUID'
sudo fdisk -l 

echo "Swap NEW UUID WITH OLD"
xterm 'sudo nano /etc/fstab'
