#!/bin/bash

# Unmount prtitions first
#sudo umount /dev/sda2
#sudo umount /dev/sda3

# Backup the original GRUB configuration file
sudo cp /boot/grub/grub.cfg /boot/grub/grub.cfg.bak

# Generate a new GRUB configuration file
sudo grub-mkconfig -o /boot/grub/grub.cfg

# Get the UUID of the new root partition
new_root_uuid=$(sudo blkid -s UUID -o value /dev/sda3)

# Update the GRUB configuration file
sudo sed -i "s/ROOT=UUID=[a-zA-Z0-9\-]*/ROOT=UUID=$new_root_uuid/" /boot/grub/grub.cfg

# Display the modified GRUB configuration file
cat /boot/grub/grub.cfg

# Check your changes first
echo "UPDATE GRUB:> sudo update-grub"
